config/routes.rb
Rails.application.routes.draw do
  root 'home#user_feed'
  get 'application/facebook_logout', :as => :facebook_logout
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new'
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :omniauth_destroy_user_session

  end
  resources :users
  get 'home/index'
  get 'home/user_feed'
  get 'home/gotham'
  get 'home/got'
  get 'home/contact'

  

end

app/views/layouts/_entries.html.erb
<% if user_signed_in? %>

<div id="page">
	<div id="page-bgtop">
		<div id="page-bgbtm">
			<div id="content">
				<div class="post">
					
					<h2 class="title"><%= @new_feed.title %></h2>
					<!-- <p class="meta">Here are the entries</p> -->
					

					<div class="entry">
						<%= form_tag({controller: "home", action: "user_feed"}, method: "get", remote: true) do  %>
							<p>Select show: <%#= select_tag "shows", options_from_collection_for_select(@shows, "value","name") %>
							<%= select_tag "shows", options_from_collection_for_select(@shows, "value","name"), {include_blank: true}%>
							<%#= select "shows", Show.all.collect {|p| [ p.name, p.value ] }, { include_blank: true }%>
							</p>
							
							<p>
								<%= submit_tag "select", class: "btn btn-primary"%>
							</p>
						<% end %>
					</div>

					<% @entries.each do |entry| %>
						<div class="entry">
							<p>Episode name: <%=entry.title%></p>
							<p>Episode link: <%= link_to 'download link', entry.url %></p>
							<p>Published at: <%= entry.published %></p>
						</div>
					<% end %>

				</div>
				
			</div>
<% else %>
	<div id="page">
		<div id="page-bgtop">
			<div id="page-bgbtm">
				<div id="content">
					<h2 class="title">You need to sign in before continuing</h2>
				</div>
			</div>
		</div>
	</div>
<% end %>			

	    <%= render 'layouts/sidebar' %>

app/views/layouts/_footer.html.erb
<div style="clear: both;">&nbsp;</div>
		</div>
		<!-- end #page -->
	</div>
</div>
<div id="footer-bgcontent">
	<div id="footer">
		<p>&copy; Untitled. All rights reserved. Design by <a href="http://templated.co" rel="nofollow">TEMPLATED</a> and <a href="https://icons8.com">Icon pack by Icons8</a>.</p>
	</div>
	<!-- end #footer -->

app/views/layouts/_header.html.erb
<div id="header">
	<div id="menu">
		<ul>
		
			<li>
				
				<%= link_to 'About', home_contact_path %>
			</li>
			<% if user_signed_in? %>
			
			
			<li>

				<% if session[:current_provider] == 'facebook' %>
					<%#= link_to 'Log out', facebook_logout_url, method: :get %>
					<%= link_to 'Log out', destroy_user_session_url, method: :delete %>
				<% else %>
					<%= link_to 'Log out', destroy_user_session_url, method: :delete %>
				<%#= link_to 'Log out', destroy_user_session_url, method: :delete %>
					
				<% end %>	
			</li>
			<% end %>
		</ul>
	</div>
	<!-- end #menu -->
	<div id="logo">
		<h1><a href="#">Show Feeds</a></h1>
		
	</div>
	<hr />
</div>
<!-- end #header -->
<!-- end #header-wrapper -->
<!-- end #logo -->

app/views/layouts/_sidebar.html.erb
<div id="sidebar">
				<ul>
					<li>
						<h2>About this tool</h2>
						<div id="bg1">
							<div id="bg2">
								<p>Just select any TV show from selection and you will get list of latest episodes released with it's release date.</p>
							</div>
						</div>
					</li>
					<li>
						<h2>Popular TV shows</h2>
						<div id="bg1">
							<div id="bg2">
								<ul>
									<li><%= link_to 'Arrow', home_index_url %></li>
									<li><%= link_to 'Game Of Thrones', home_got_url %></li>
									<li><%= link_to 'Gotham feed', home_gotham_url %></li>
								</ul>
							</div>
						</div>
					</li>
					<li>
						<h2>Favourites</h2>
						<div id="bg1">
							<div id="bg2">
								<ul>
									
									<!-- <li><a href="#">Nec metus sed donec</a></li>
									<li><a href="#">Magna lacus bibendum mauris</a></li>
									<li><a href="#">Velit semper nisi molestie</a></li>
									<li><a href="#">Eget tempor eget nonummy</a></li>
									<li><a href="#">Nec metus sed donec</a></li>
									<li><a href="#">Nec metus sed donec</a></li>
									<li><a href="#">Magna lacus bibendum mauris</a></li>
									<li><a href="#">Velit semper nisi molestie</a></li>
									<li><a href="#">Eget tempor eget nonummy</a></li>
									<li><a href="#">Nec metus sed donec</a></li>
									 -->
								</ul>
							</div>
						</div>
					</li>
				</ul>
			</div>
			<!-- end #sidebar -->
			

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyFeeds</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'style.css', media: 'screen' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>
			
<div id="footer-bgcontent">
	<div id="footer">
		<p class="notice"><%= notice %></p>
		<p class="alert"><%= alert %></p>
	</div>
</div>
<%= yield %>

<%= render 'layouts/footer' %>

</div>
</body>
</html>